import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:simple_card_game/services/game_client.dart';
import 'package:simple_card_game/ui/screens/network_game_screen.dart';
import 'package:simple_card_game/ui/theme/game_theme.dart';

/// DEV-ONLY visual-iteration harness (`?netboard=1`).
///
/// Renders the real [NetworkGameScreen] from a CANNED redacted-state fixture
/// (`assets/fixtures/net_board.json`, generated by
/// `server/tool/gen_board_fixture.dart` via the server's real `redactFor`), so
/// the networked board can be screenshotted with real card art and the exact
/// server state shape — no server or WebSocket needed. Action buttons no-op
/// (the fake client has no socket), which is fine for static capture.
///
/// Not reachable in normal play; only via the `?netboard=1` URL param.
class NetBoardFixtureScreen extends StatefulWidget {
  const NetBoardFixtureScreen({super.key, this.fixture = 'net_board'});

  /// Fixture file stem under assets/fixtures/ (default `net_board`).
  final String fixture;

  @override
  State<NetBoardFixtureScreen> createState() => _NetBoardFixtureScreenState();
}

class _NetBoardFixtureScreenState extends State<NetBoardFixtureScreen> {
  GameClient? _client;
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    try {
      final raw = await rootBundle
          .loadString('assets/fixtures/${widget.fixture}.json');
      final state = (jsonDecode(raw) as Map).cast<String, dynamic>();
      // The fixture is p<n>'s view; authenticate the fake client as that seat so
      // `isMyTurn` etc. resolve correctly.
      final me = state['you'] as String? ?? 'p0';
      final client = GameClient(playerId: me)..gameState = state;
      setState(() => _client = client);
    } catch (e) {
      setState(() => _error = '$e');
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_error != null) {
      return Scaffold(
        backgroundColor: GameTheme.boardBackground,
        body: Center(
          child: Text('fixture load failed:\n$_error',
              style: const TextStyle(color: Colors.redAccent)),
        ),
      );
    }
    final client = _client;
    if (client == null) {
      return const Scaffold(
        backgroundColor: GameTheme.boardBackground,
        body: Center(child: CircularProgressIndicator()),
      );
    }
    return NetworkGameScreen(client: client);
  }
}
