// Generates the card-coverage README (assets/card_db/COVERAGE.md) from the
// authoritative card database (assets/card_db/cards.json).
//
// Run from the project root:
//   dart run tool/gen_coverage_readme.dart
//
// The README encodes, per card, whether it has art, encoded effects, raw text,
// and human verification, plus per-set and per-faction rollups. Regenerate it
// after every data-entry pass so the coverage table never drifts from the data.

import 'dart:convert';
import 'dart:io';

const String outPath = 'assets/card_db/COVERAGE.md';

void main(List<String> args) {
  final path = args.isNotEmpty ? args.first : 'assets/card_db/cards.json';
  final file = File(path);
  if (!file.existsSync()) {
    stderr.writeln('ERROR: $path not found');
    exit(1);
  }

  final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final cards = (data['cards'] as List<dynamic>? ?? const [])
      .cast<Map<String, dynamic>>();

  bool hasArt(Map<String, dynamic> c) {
    final a = c['art'];
    return a is String && a.trim().isNotEmpty;
  }

  bool hasEffects(Map<String, dynamic> c) {
    final e = c['playEffects'];
    return e is List && e.isNotEmpty;
  }

  bool hasRaw(Map<String, dynamic> c) {
    final r = c['rawText'];
    return r is String && r.trim().isNotEmpty;
  }

  bool isVerified(Map<String, dynamic> c) => c['verified'] == true;

  final total = cards.length;
  final artCount = cards.where(hasArt).length;
  final effCount = cards.where(hasEffects).length;
  final rawCount = cards.where(hasRaw).length;
  final verCount = cards.where(isVerified).length;

  // Per-set rollup.
  final setOrder = <String>[];
  final bySet = <String, List<Map<String, dynamic>>>{};
  for (final c in cards) {
    final s = (c['set'] as String?) ?? 'unknown';
    bySet.putIfAbsent(s, () {
      setOrder.add(s);
      return [];
    }).add(c);
  }
  setOrder.sort();

  // Per-faction rollup.
  final byFaction = <String, List<Map<String, dynamic>>>{};
  for (final c in cards) {
    final f = (c['faction'] as String?) ?? 'none';
    byFaction.putIfAbsent(f, () => []).add(c);
  }
  final factionOrder = byFaction.keys.toList()..sort();

  String pct(int n, int d) =>
      d == 0 ? '—' : '${(100 * n / d).toStringAsFixed(0)}%';

  String rollupRow(String label, List<Map<String, dynamic>> group) {
    final n = group.length;
    final a = group.where(hasArt).length;
    final e = group.where(hasEffects).length;
    final r = group.where(hasRaw).length;
    final v = group.where(isVerified).length;
    return '| $label | $n | $a (${pct(a, n)}) | $e (${pct(e, n)}) | '
        '$r (${pct(r, n)}) | $v (${pct(v, n)}) |';
  }

  final b = StringBuffer();
  b.writeln('# Card Database Coverage');
  b.writeln();
  b.writeln('_Auto-generated by `tool/gen_coverage_readme.dart` from '
      '`cards.json`. Do not edit by hand — regenerate after each data pass:_');
  b.writeln();
  b.writeln('```bash');
  b.writeln('dart run tool/gen_coverage_readme.dart');
  b.writeln('```');
  b.writeln();
  b.writeln('## Overall');
  b.writeln();
  b.writeln('| Dimension | Covered | Total | % |');
  b.writeln('|-----------|--------:|------:|--:|');
  b.writeln('| Art on disk | $artCount | $total | ${pct(artCount, total)} |');
  b.writeln('| Effects encoded | $effCount | $total | ${pct(effCount, total)} |');
  b.writeln('| Raw text captured | $rawCount | $total | ${pct(rawCount, total)} |');
  b.writeln('| **Verified** | **$verCount** | **$total** | **${pct(verCount, total)}** |');
  b.writeln();
  b.writeln('Legend: **Art** = card image present · **Eff** = `playEffects` '
      'encoded · **Raw** = printed text transcribed · **Ver** = human-confirmed '
      'against the physical card.');
  b.writeln();

  b.writeln('## By set');
  b.writeln();
  b.writeln('| Set | Cards | Art | Eff | Raw | Ver |');
  b.writeln('|-----|------:|----:|----:|----:|----:|');
  for (final s in setOrder) {
    b.writeln(rollupRow('`$s`', bySet[s]!));
  }
  b.writeln();

  b.writeln('## By faction');
  b.writeln();
  b.writeln('| Faction | Cards | Art | Eff | Raw | Ver |');
  b.writeln('|---------|------:|----:|----:|----:|----:|');
  for (final f in factionOrder) {
    b.writeln(rollupRow('`$f`', byFaction[f]!));
  }
  b.writeln();

  b.writeln('## Per-card matrix');
  b.writeln();
  b.writeln('Ordered by set, then id. ✓ = present, · = missing.');
  b.writeln();
  final sortedCards = [...cards]..sort((x, y) {
      final sx = (x['set'] as String?) ?? 'unknown';
      final sy = (y['set'] as String?) ?? 'unknown';
      final c = sx.compareTo(sy);
      return c != 0 ? c : (x['id'] as String).compareTo(y['id'] as String);
    });
  b.writeln('| id | set | faction | type | Art | Eff | Raw | Ver |');
  b.writeln('|----|-----|---------|------|:---:|:---:|:---:|:---:|');
  String m(bool v) => v ? '✓' : '·';
  for (final c in sortedCards) {
    final id = c['id'] as String;
    final set = (c['set'] as String?) ?? '—';
    final fac = (c['faction'] as String?) ?? '—';
    final type = (c['cardType'] as String?) ?? '—';
    b.writeln('| `$id` | $set | $fac | $type | ${m(hasArt(c))} | '
        '${m(hasEffects(c))} | ${m(hasRaw(c))} | ${m(isVerified(c))} |');
  }
  b.writeln();

  File(outPath).writeAsStringSync(b.toString());
  stdout.writeln('Wrote $outPath '
      '($total cards: art $artCount, eff $effCount, raw $rawCount, ver $verCount)');
}
